# Generated by Django 5.2 on 2025-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('photo', 'photo'), ('video', 'video')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
