# Generated by Django 5.2 on 2025-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_story_duration_story_story_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_url',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
