# Generated by Django 5.2 on 2025-05-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0012_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
